steps:
  # 1. Initialize Terraform with a GCS backend
  # This step sets up Terraform to use your GCS bucket for state storage.
  - name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'terraform'
    args:
      - 'init'
      - '-backend-config=bucket=${_TF_STATE_BUCKET}'

  # 2. Run Terraform Plan
  # This step generates an execution plan and saves it to a file.
  # The secret 'my-secret' is made available as an environment variable billing_account_id.
  - name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
    secretEnv: ['billing_account_id']

  # 3. Run Terraform Apply
  # This step applies the changes defined in the plan file.
  - name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', 'tfplan']
    secretEnv: ['billing_account_id']

# This section makes secrets from Secret Manager available to the build steps.
availableSecrets:
  secretManager:
  - versionName: projects/YOUR_PROJECT_ID/secrets/billing-id/versions/latest
    env: 'billing_account_id' # Maps the secret value to this environment variable

# Recommended settings
options:
  logging: CLOUD_LOGGING_ONLY